### ISSUE TITLE
You are not signed in :(

### ISSUE THREAD

**Issue by ziiicos** [grzeg1/polarsync#1]
Hi, 
Based on your code I've got an issue when executing curl statement 

https://flow.polar.com/training/getCalendarEvents

reponsecode = 400
response={"message":"You are not signed in. You are redirected to the sign-in page in 5 seconds.","redirect":"/"}

The first 2 exec are OK (reponsecode 200)
Is there anything wrong in my code or Polar changed something from their side ?

Thks in advance
Florent

$post_fields = 'returnUrl=https%3A%2F%2Fflow.polar.com%2F&email=' . $strUsername . '&password=' . $strPassword;
        $curl = curl_init();
        curl_setopt($curl, CURLOPT_USERAGENT, 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36');
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($curl, CURLOPT_POST, 0);
        curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($curl, CURLOPT_URL, 'https://flow.polar.com/ajaxLogin');
        $response = curl_exec($curl); //get login page
        $responsecode 	= curl_getinfo($curl, CURLINFO_HTTP_CODE);
	if (curl_errno($curl)) {
		// Le message d'erreur correspondant est affiché
		var_dump("ERREUR curl_exec 1 : ".curl_error($curl));
	}
        else {
            var_dump("1:responsecode=".$responsecode);
            var_dump("1:response=".$response);
        }
        //curl_close($curl);
        
        //$curl = curl_init();
        curl_setopt($curl, CURLOPT_URL, 'https://flow.polar.com/login');
        curl_setopt($curl, CURLOPT_POST, 1);
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($curl, CURLOPT_POSTFIELDS, $post_fields);
        $response = curl_exec($curl); //post credentials
        $responsecode 	= curl_getinfo($curl, CURLINFO_HTTP_CODE);
	if (curl_errno($curl)) {
		// Le message d'erreur correspondant est affiché
		var_dump("ERREUR curl_exec 2 : ".curl_error($curl));
	}
        else {
            var_dump("2:responsecode=".$responsecode);
            var_dump("2:response=".$response);
        }
        
        //$curl = curl_init();
        curl_setopt($curl, CURLOPT_POST, 0);
        $weekago = time() - 7 * 24 * 60 * 60;
        $end_date = date('d.m.Y');
        $start_date = date('d.m.Y', $weekago);
        curl_setopt($curl, CURLOPT_URL, 'https://flow.polar.com/training/getCalendarEvents?start=' . $start_date . '&end=' . $end_date);
        //var_dump('https://flow.polar.com/training/getCalendarEvents?start=' . $start_date . '&end=' . $end_date);exit;
        $response = curl_exec($curl); //get activity list
        $responsecode 	= curl_getinfo($curl, CURLINFO_HTTP_CODE);
	if (curl_errno($curl)) {
		// Le message d'erreur correspondant est affiché
		var_dump("ERREUR curl_exec 2 : ".curl_error($curl));
	}
        else {
            var_dump("3:responsecode=".$responsecode);
            var_dump("3:response=".$response);
            var_dump("3:responseJSON=".json_decode($response));
        }

**Comment by grzeg1** [comment]
2 things come to my mind:
- issue with Flow (sometimes it does not work)
- cookie file path is not set correctly/not writable

**Comment by grzeg1** [comment]
no response from reporter
