### ISSUE TITLE
Sync fails after flow update 

### ISSUE THREAD

**Issue by steffenr** [grzeg1/polarsync#2]
After the flow webservice update the sync is no longer working. The URL to the ZIP file exports changed.

Instead of 
```php
 $tcxzipurl = 'https://flow.polar.com' . $activity->url . '/export/tcx';
```
you have to use 
```php
 $tcxzipurl = 'https://flow.polar.com' . $activity->url . '/export/tcx/true';
```

After changing the url sync is working fine for me..

**Comment by grzeg1** [comment]
Thanks.
Fixed via #3
